### ISSUE TITLE
PublicationStatus

### ISSUE THREAD

**Issue by VincentFarcy** [chemins-de-la-transition/ontology#19]
nouveau concept `PublicationStatus` avec relations `hasPublicationStatus` / `publicationStatusOn`
Types de ressource concernés : 
- `Course`
- `Event`
- `Place`
- `Path`
- `Organization`

En lien avec https://github.com/chemins-de-la-transition/semapps/issues/551

**Comment by GuillaumeAV** [comment]
Ayé j'ai mis à jour l'ontologie avec la nouvelle classe ! http://virtual-assembly.org/ontologies/cdlt#PublicationStatus
Cf https://github.com/chemins-de-la-transition/ontology/blob/main/Ontologie_Chemins_de_la_Transition_v0.1.owl
